import { Request, Response } from "express";
import { UserService } from "../services/user.services";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { AppError } from "../utils/AppError";

const JWT_SECRET = process.env.JWT_SECRET || "change_this_secret";

export class AuthController {
  private userService = new UserService();

  async register(req: Request, res: Response) {
    const { name, email, password } = req.body;
    if (!name || !email || !password) {
      throw new AppError("Missing fields", 400);
    }

    const existing = await this.userService.getUserByEmail(email);
    if (existing) {
      throw new AppError("Email in use", 409);
    }

    const hashed = await bcrypt.hash(password, 10);
    // id is auto-generated by DB
    await this.userService.createUser({
      name,
      email,
      password: hashed,
      role: false,
    });
    return res.status(201).json({ message: "User registered" });
  }

  async login(req: Request, res: Response) {
    const { email, password } = req.body;
    if (!email || !password) {
      throw new AppError("Missing email or password", 400);
    }

    const user = await this.userService.getUserByEmail(email);
    if (!user) {
      throw new AppError("Invalid credentials", 401);
    }

    if (!user.password) {
      console.error("User found but has no password hash stored:", email);
      throw new AppError("Account error", 500);
    }

    const ok = await bcrypt.compare(password, user.password);
    if (!ok) {
      throw new AppError("Invalid credentials", 401);
    }

    const payload = {
      idUser: user.idUser,
      email: user.email,
      role: user.role,
    };
    const token = jwt.sign(payload, JWT_SECRET, { expiresIn: "8h" });
    return res.status(200).json({
      token,
      user: {
        idUser: user.idUser,
        name: user.name,
        email: user.email,
        role: user.role,
      },
    });
  }

  // -------------------------------------------------------
  // password recovery endpoints
  // -------------------------------------------------------

  /**
   * initiate password reset by email
   * returns a token (in real app would email the link)
   */
  async forgotPassword(req: Request, res: Response) {
    const { email } = req.body;
    if (!email) {
      throw new AppError("Email required", 400);
    }

    const user = await this.userService.getUserByEmail(email);
    // always respond successfully to avoid leaking which emails exist
    if (!user) {
      return res.status(200).json({
        message: "If that email is registered, a reset link has been sent",
      });
    }

    const token = jwt.sign({ idUser: user.idUser }, JWT_SECRET, {
      expiresIn: "1h",
    });
    // TODO: send token to user via email. For now we return it for testing
    console.log(`Password reset token for ${email}: ${token}`);
    return res.status(200).json({ message: "Reset token generated", token });
  }

  /**
   * complete password reset using token
   */
  async resetPassword(req: Request, res: Response) {
    const { token, newPassword } = req.body;
    if (!token || !newPassword) {
      throw new AppError("Token and new password required", 400);
    }

    let payload: any;
    try {
      payload = jwt.verify(token, JWT_SECRET) as any;
    } catch (err) {
      throw new AppError("Invalid or expired token", 400);
    }

    const user = await this.userService.getUserById(payload.idUser);
    if (!user) {
      throw new AppError("User not found", 404);
    }

    const hashed = await bcrypt.hash(newPassword, 10);
    await this.userService.updateUser(user.idUser, { password: hashed });
    return res.status(200).json({ message: "Password has been reset" });
  }
}

export default new AuthController();
